services:
  frontend:
    build:
      context: ../
      dockerfile: ./infrastructure/Dockerfile
    image: ${COMPOSE_PROJECT_NAME}
    container_name: ${COMPOSE_PROJECT_NAME}
    ports:
      - 80:8080
    volumes:
      - ../src:/usr/src
    command: npm run dev
